[package]
name = "industrial-robots"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k = "0.30.0"

[dev-dependencies]
test-case = "3.1.0"
approx = "0.5.1"
rand = "0.8.5"